# Generated by Django 3.0.4 on 2020-05-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmanager', '0002_auto_20200510_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmanager',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
