# Generated by Django 3.0.4 on 2020-05-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20200512_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='fuel_count',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
