# Generated by Django 3.0.4 on 2020-05-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20200514_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carslist',
            name='fuel_count',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
