# Generated by Django 3.0.4 on 2020-05-13 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20200514_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='carslist',
            name='transmission',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
